PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE source (source_id INTEGER PRIMARY KEY AUTOINCREMENT, sources TEXT UNIQUE NOT NULL);
INSERT INTO source VALUES(1,'1790 US Census');
INSERT INTO source VALUES(2,'1800 US Census');
INSERT INTO source VALUES(3,'1810 US Census');
INSERT INTO source VALUES(4,'1820 US Census');
INSERT INTO source VALUES(5,'1830 US Census');
INSERT INTO source VALUES(6,'1840 US Census');
INSERT INTO source VALUES(7,'1850 US Census');
INSERT INTO source VALUES(8,'1860 US Census');
INSERT INTO source VALUES(9,'1870 US Census');
INSERT INTO source VALUES(10,'1880 US Census');
INSERT INTO source VALUES(11,'1890 US Census');
INSERT INTO source VALUES(12,'1900 US Census');
INSERT INTO source VALUES(13,'1910 US Census');
INSERT INTO source VALUES(14,'1920 US Census');
INSERT INTO source VALUES(15,'1930 US Census');
INSERT INTO source VALUES(16,'1940 US Census');
INSERT INTO source VALUES(17,'1950 US Census');
INSERT INTO source VALUES(18,'1960 US Census');
INSERT INTO source VALUES(19,'1970 US Census');
INSERT INTO source VALUES(20,'1980 US Census');
INSERT INTO source VALUES(21,'1990 US Census');
INSERT INTO source VALUES(22,'2000 US Census');
INSERT INTO source VALUES(23,'2010 US Census');
INSERT INTO source VALUES(24,'2020 US Census');
INSERT INTO source VALUES(25,'2030 US Census');
INSERT INTO source VALUES(26,'2040 US Census');
INSERT INTO source VALUES(27,'2050 US Census');
INSERT INTO source VALUES(28,'2060 US Census');
INSERT INTO source VALUES(29,'2070 US Census');
CREATE TABLE image (image_id INTEGER PRIMARY KEY AUTOINCREMENT, images TEXT UNIQUE NOT NULL, caption TEXT);
INSERT INTO image VALUES(14,'default_image_unisex.jpg','Add a photo--how about a vintage photo of where this person lived?');
INSERT INTO image VALUES(15,'default_image_female.jpg','Add a photo--how about a vintage photo of where this person lived?');
INSERT INTO image VALUES(17,'default_image_male.gif','Add a photo--how about a vintage photo of where this person lived?');
INSERT INTO image VALUES(18,'default_image_source.jpg','Add a photo--how about a vintage photo of where this person lived?');
INSERT INTO image VALUES(19,'default_image_place.jpg','Add a photo--how about a vintage photo of where this person lived?');
CREATE TABLE event_type (event_type_id INTEGER PRIMARY KEY AUTOINCREMENT, event_types TEXT UNIQUE NOT NULL, built_in BOOLEAN NOT NULL DEFAULT 0, hidden BOOLEAN NOT NULL DEFAULT 0, couple BOOLEAN NOT NULL DEFAULT 0, after_death BOOLEAN NOT NULL DEFAULT 0, marital BOOLEAN NOT NULL DEFAULT 0);
INSERT INTO event_type VALUES(1,'birth',1,0,0,0,0);
INSERT INTO event_type VALUES(2,'marriage',1,0,1,0,1);
INSERT INTO event_type VALUES(3,'illness',1,0,0,0,0);
INSERT INTO event_type VALUES(4,'death',1,0,0,0,0);
INSERT INTO event_type VALUES(5,'burial',1,0,0,1,0);
INSERT INTO event_type VALUES(6,'occupation',1,0,0,0,0);
INSERT INTO event_type VALUES(7,'imprisonment',1,0,0,0,0);
INSERT INTO event_type VALUES(8,'deportation',1,0,0,0,0);
INSERT INTO event_type VALUES(9,'invention',1,0,0,0,0);
INSERT INTO event_type VALUES(10,'religious conversion',1,0,0,0,0);
INSERT INTO event_type VALUES(11,'wedding',1,0,1,0,1);
INSERT INTO event_type VALUES(12,'ran away from home',1,0,0,0,0);
INSERT INTO event_type VALUES(13,'residence',1,0,0,0,0);
INSERT INTO event_type VALUES(15,'divorce',1,0,1,0,1);
INSERT INTO event_type VALUES(16,'engagement',1,0,1,0,0);
INSERT INTO event_type VALUES(17,'annulment',1,0,1,0,1);
INSERT INTO event_type VALUES(18,'separation',1,0,1,0,1);
INSERT INTO event_type VALUES(19,'eye color',1,0,0,0,0);
INSERT INTO event_type VALUES(20,'hair color',1,0,0,0,0);
INSERT INTO event_type VALUES(21,'height',1,0,0,0,0);
INSERT INTO event_type VALUES(22,'weight',1,0,0,0,0);
INSERT INTO event_type VALUES(23,'build',1,0,0,0,0);
INSERT INTO event_type VALUES(24,'complexion',1,0,0,0,0);
INSERT INTO event_type VALUES(25,'race',1,0,0,0,0);
INSERT INTO event_type VALUES(26,'ethnic origin',1,0,0,0,0);
INSERT INTO event_type VALUES(27,'marks, scars',1,0,0,0,0);
INSERT INTO event_type VALUES(28,'disability',1,0,0,0,0);
INSERT INTO event_type VALUES(29,'condition',1,0,0,0,0);
INSERT INTO event_type VALUES(30,'religion',1,0,0,0,0);
INSERT INTO event_type VALUES(31,'career',1,0,0,0,0);
INSERT INTO event_type VALUES(32,'number of children, total',1,0,0,0,0);
INSERT INTO event_type VALUES(33,'number of children, living',1,0,0,0,0);
INSERT INTO event_type VALUES(34,'marital status',1,0,0,0,0);
INSERT INTO event_type VALUES(35,'political affiliation',1,0,0,0,0);
INSERT INTO event_type VALUES(36,'special talent',1,0,0,0,0);
INSERT INTO event_type VALUES(37,'hobby',1,0,0,0,0);
INSERT INTO event_type VALUES(38,'able to read',1,0,0,0,0);
INSERT INTO event_type VALUES(39,'able to write',1,0,0,0,0);
INSERT INTO event_type VALUES(40,'first language',1,0,0,0,0);
INSERT INTO event_type VALUES(41,'nationality',1,0,0,0,0);
INSERT INTO event_type VALUES(42,'education level',1,0,0,0,0);
INSERT INTO event_type VALUES(43,'draft registration',1,0,0,0,0);
INSERT INTO event_type VALUES(44,'legal problem',1,0,0,0,0);
INSERT INTO event_type VALUES(45,'tobacco use',1,1,0,0,0);
INSERT INTO event_type VALUES(46,'alcohol use',1,1,0,0,0);
INSERT INTO event_type VALUES(47,'drug problem',1,1,0,0,0);
INSERT INTO event_type VALUES(53,'jury duty',1,0,0,0,0);
INSERT INTO event_type VALUES(54,'baptism',1,0,0,0,0);
INSERT INTO event_type VALUES(55,'excommunication',1,0,0,0,0);
INSERT INTO event_type VALUES(56,'betrothal',1,0,1,0,0);
INSERT INTO event_type VALUES(57,'resignation',1,0,0,0,0);
INSERT INTO event_type VALUES(58,'naturalization',1,0,0,0,0);
INSERT INTO event_type VALUES(59,'marriage license',1,0,1,0,1);
INSERT INTO event_type VALUES(60,'christening',1,0,0,0,0);
INSERT INTO event_type VALUES(61,'confirmation',1,0,0,0,0);
INSERT INTO event_type VALUES(62,'cremation',1,0,0,1,0);
INSERT INTO event_type VALUES(63,'will',1,0,0,0,0);
INSERT INTO event_type VALUES(64,'retirement',1,0,0,0,0);
INSERT INTO event_type VALUES(65,'ordination',1,0,0,0,0);
INSERT INTO event_type VALUES(66,'graduation',1,0,0,0,0);
INSERT INTO event_type VALUES(67,'emigration',1,0,0,0,0);
INSERT INTO event_type VALUES(68,'probate',1,0,0,1,0);
INSERT INTO event_type VALUES(69,'enrollment',1,0,0,0,0);
INSERT INTO event_type VALUES(70,'execution',1,0,0,0,0);
INSERT INTO event_type VALUES(71,'employment',1,0,0,0,0);
INSERT INTO event_type VALUES(72,'land grant',1,0,0,0,0);
INSERT INTO event_type VALUES(73,'name change',1,0,0,0,0);
INSERT INTO event_type VALUES(74,'land purchase',1,0,0,0,0);
INSERT INTO event_type VALUES(75,'land sale',1,0,0,0,0);
INSERT INTO event_type VALUES(76,'military induction',1,0,0,0,0);
INSERT INTO event_type VALUES(77,'military enlistment',1,0,0,0,0);
INSERT INTO event_type VALUES(78,'military discharge',1,0,0,0,0);
INSERT INTO event_type VALUES(79,'military promotion',1,0,0,0,0);
INSERT INTO event_type VALUES(80,'military service',1,0,0,0,0);
INSERT INTO event_type VALUES(81,'marriage banns',1,0,1,0,0);
INSERT INTO event_type VALUES(82,'missing in action',1,0,0,0,0);
INSERT INTO event_type VALUES(83,'adoption',1,0,0,0,0);
INSERT INTO event_type VALUES(84,'reburial',1,0,0,1,0);
INSERT INTO event_type VALUES(85,'filing for divorce',1,0,1,0,1);
INSERT INTO event_type VALUES(86,'reading of the will',1,0,0,1,0);
INSERT INTO event_type VALUES(87,'exhumation',1,0,0,1,0);
INSERT INTO event_type VALUES(88,'funeral',1,0,0,1,0);
INSERT INTO event_type VALUES(89,'celebration of life',1,0,0,1,0);
INSERT INTO event_type VALUES(90,'partnership',1,0,1,0,1);
INSERT INTO event_type VALUES(91,'natural disaster',1,0,0,0,0);
INSERT INTO event_type VALUES(93,'anniversary celebration',1,0,1,0,1);
INSERT INTO event_type VALUES(95,'offspring',1,0,0,0,0);
INSERT INTO event_type VALUES(96,'posthumous offspring',1,0,0,1,0);
INSERT INTO event_type VALUES(100,'scattering of ashes',1,0,0,1,0);
INSERT INTO event_type VALUES(101,'inurnment',1,0,0,1,0);
INSERT INTO event_type VALUES(102,'cohabitation',1,0,1,0,1);
INSERT INTO event_type VALUES(103,'living together',1,0,1,0,1);
INSERT INTO event_type VALUES(104,'wedding anniversary',1,0,1,0,1);
INSERT INTO event_type VALUES(105,'shacking up',1,1,1,0,1);
CREATE TABLE kin_type (kin_type_id INTEGER PRIMARY KEY AUTOINCREMENT, kin_types TEXT UNIQUE NOT NULL, kin_code TEXT NOT NULL, hidden BOOLEAN NOT NULL DEFAULT 0);
INSERT INTO kin_type VALUES(1,'mother','B',0);
INSERT INTO kin_type VALUES(2,'father','B',0);
INSERT INTO kin_type VALUES(3,'parent','B',0);
INSERT INTO kin_type VALUES(4,'daughter','E',0);
INSERT INTO kin_type VALUES(5,'son','E',0);
INSERT INTO kin_type VALUES(6,'child','E',0);
INSERT INTO kin_type VALUES(7,'wife','D',0);
INSERT INTO kin_type VALUES(8,'husband','D',0);
INSERT INTO kin_type VALUES(9,'spouse','D',0);
INSERT INTO kin_type VALUES(10,'mate','D',0);
INSERT INTO kin_type VALUES(11,'sister','C',0);
INSERT INTO kin_type VALUES(12,'brother','C',0);
INSERT INTO kin_type VALUES(13,'sibling','C',0);
INSERT INTO kin_type VALUES(14,'partner','D',0);
INSERT INTO kin_type VALUES(15,'common-law spouse','D',0);
INSERT INTO kin_type VALUES(16,'fiance','D',0);
INSERT INTO kin_type VALUES(17,'fiancee','D',0);
INSERT INTO kin_type VALUES(18,'boyfriend','D',0);
INSERT INTO kin_type VALUES(19,'girlfriend','D',0);
INSERT INTO kin_type VALUES(20,'lady friend','D',0);
INSERT INTO kin_type VALUES(21,'lover','D',1);
INSERT INTO kin_type VALUES(22,'mistress','D',0);
INSERT INTO kin_type VALUES(23,'betrothed','D',0);
INSERT INTO kin_type VALUES(24,'bride','D',0);
INSERT INTO kin_type VALUES(25,'groom','D',0);
INSERT INTO kin_type VALUES(123,'generic_partner1','D',1);
INSERT INTO kin_type VALUES(124,'generic_partner2','D',1);
CREATE TABLE name_type (name_type_id INTEGER PRIMARY KEY AUTOINCREMENT, name_types TEXT UNIQUE DEFAULT '');
INSERT INTO name_type VALUES(1,'birth name');
INSERT INTO name_type VALUES(2,'also known as');
INSERT INTO name_type VALUES(3,'pseudonym');
INSERT INTO name_type VALUES(4,'ID number');
INSERT INTO name_type VALUES(5,'adoptive name');
INSERT INTO name_type VALUES(6,'married name');
INSERT INTO name_type VALUES(7,'handle');
INSERT INTO name_type VALUES(8,'alternate spelling');
INSERT INTO name_type VALUES(9,'mis-spelling');
INSERT INTO name_type VALUES(10,'legally changed name');
INSERT INTO name_type VALUES(11,'stage name');
INSERT INTO name_type VALUES(12,'nickname');
INSERT INTO name_type VALUES(13,'call name');
INSERT INTO name_type VALUES(14,'official name');
INSERT INTO name_type VALUES(15,'anglicized name');
INSERT INTO name_type VALUES(16,'unknown name');
INSERT INTO name_type VALUES(17,'religious order name');
INSERT INTO name_type VALUES(18,'other name type');
INSERT INTO name_type VALUES(19,'wrong name');
INSERT INTO name_type VALUES(20,'pen name');
INSERT INTO name_type VALUES(21,'given name');
INSERT INTO name_type VALUES(22,'reference name');
CREATE TABLE person (PERSON_ID integer primary key autoincrement, gender TEXT NOT NULL DEFAULT 'unknown');
INSERT INTO person VALUES(1,'unknown');
CREATE TABLE role_type (
       role_type_id INTEGER PRIMARY KEY AUTOINCREMENT, 
       role_types TEXT UNIQUE NOT NULL, built_in BOOLEAN NOT NULL DEFAULT 0, hidden BOOLEAN NOT NULL DEFAULT 0);
INSERT INTO role_type VALUES(1,'religious officer',1,0);
INSERT INTO role_type VALUES(2,'justice of the peace',1,0);
INSERT INTO role_type VALUES(3,'arresting officer',1,0);
INSERT INTO role_type VALUES(4,'supervisor',1,0);
INSERT INTO role_type VALUES(5,'employer',1,0);
INSERT INTO role_type VALUES(6,'midwife',1,0);
INSERT INTO role_type VALUES(7,'bridesmaid',1,0);
INSERT INTO role_type VALUES(8,'best man',1,0);
INSERT INTO role_type VALUES(9,'bible bearer',1,0);
INSERT INTO role_type VALUES(10,'flower girl',1,0);
INSERT INTO role_type VALUES(11,'witness',1,0);
INSERT INTO role_type VALUES(12,'employee',1,0);
INSERT INTO role_type VALUES(13,'assistant',1,0);
INSERT INTO role_type VALUES(14,'roommate',1,0);
INSERT INTO role_type VALUES(15,'landlady',1,0);
INSERT INTO role_type VALUES(16,'landlord',1,0);
INSERT INTO role_type VALUES(17,'unknown',1,0);
INSERT INTO role_type VALUES(20,'financier',1,0);
INSERT INTO role_type VALUES(28,'chauffeur',1,0);
INSERT INTO role_type VALUES(29,'treasurer',1,0);
INSERT INTO role_type VALUES(31,'secretary',1,0);
INSERT INTO role_type VALUES(39,'neighbor',1,0);
INSERT INTO role_type VALUES(40,'maid',1,0);
INSERT INTO role_type VALUES(44,'mining partner',1,0);
INSERT INTO role_type VALUES(47,'legal guardian',1,0);
INSERT INTO role_type VALUES(55,'other',1,0);
INSERT INTO role_type VALUES(90,'driver',1,0);
INSERT INTO role_type VALUES(96,'host',1,0);
INSERT INTO role_type VALUES(97,'hostess',1,0);
INSERT INTO role_type VALUES(99,'farm hand',1,0);
INSERT INTO role_type VALUES(100,'ranch hand',1,0);
INSERT INTO role_type VALUES(103,'junior partner',1,0);
CREATE TABLE IF NOT EXISTS "date_format" (date_format_id INTEGER PRIMARY KEY AUTOINCREMENT, date_formats TEXT NOT NULL DEFAULT 'alpha_dmy', abt TEXT NOT NULL DEFAULT 'abt', est TEXT NOT NULL DEFAULT 'est', cal TEXT NOT NULL DEFAULT 'calc', bef_aft TEXT NOT NULL DEFAULT 'bef/aft', bc_ad TEXT NOT NULL DEFAULT 'BCE/CE', os_ns TEXT NOT NULL DEFAULT 'OS/NS', span TEXT NOT NULL DEFAULT 'from_to', range TEXT NOT NULL DEFAULT 'btwn_&');
INSERT INTO date_format VALUES(1,'dmy','abt','est','calc','bef/aft','BCE/CE','OS/NS','from_to','btwn_&');
CREATE TABLE IF NOT EXISTS "place" (place_id INTEGER PRIMARY KEY AUTOINCREMENT, places TEXT NOT NULL, latitude TEXT DEFAULT '', longitude TEXT DEFAULT '', cartesian_coordinates TEXT DEFAULT '', township TEXT DEFAULT '', range TEXT DEFAULT '', section TEXT DEFAULT '', legal_subdivision TEXT DEFAULT '', hint TEXT UNIQUE DEFAULT null);
INSERT INTO place VALUES(1,'unknown',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
CREATE TABLE IF NOT EXISTS "citation" (citation_id INTEGER PRIMARY KEY AUTOINCREMENT, source_id INTEGER NOT NULL, citations TEXT, FOREIGN KEY (source_id) REFERENCES source (source_id));
CREATE TABLE IF NOT EXISTS "claim" (claim_id INTEGER PRIMARY KEY AUTOINCREMENT, person_id INTEGER NOT NULL, event_type_id INTEGER NOT NULL, date TEXT, place_id INTEGER, particulars TEXT, age TEXT, citation_id INTEGER, name_id INTEGER NOT NULL, surety FLOAT DEFAULT 3.0, FOREIGN KEY (person_id) REFERENCES person (person_id), FOREIGN KEY (event_type_id) REFERENCES event_type (event_type_id), FOREIGN KEY (place_id) REFERENCES place (place_id), FOREIGN KEY (citation_id) REFERENCES citation (citation_id), FOREIGN KEY (name_id) REFERENCES name (name_id));
CREATE TABLE IF NOT EXISTS "claims_findings" (claims_findings_id INTEGER PRIMARY KEY AUTOINCREMENT, claim_id INTEGER NOT NULL, finding_id INTEGER NOT NULL, FOREIGN KEY (claim_id) REFERENCES claim (claim_id), FOREIGN KEY (finding_id) REFERENCES finding (finding_id));
CREATE TABLE IF NOT EXISTS "claims_notes" (claims_notes_id INTEGER PRIMARY KEY AUTOINCREMENT, claim_id INTEGER NOT NULL, note_id INTEGER NOT NULL, FOREIGN KEY (claim_id) REFERENCES claim (claim_id), FOREIGN KEY (note_id) REFERENCES note (note_id));
CREATE TABLE IF NOT EXISTS "claims_roles" (claims_roles_id INTEGER PRIMARY KEY AUTOINCREMENT, claim_id INTEGER NOT NULL, role_type_id INTEGER NOT NULL, person_id INTEGER NOT NULL, FOREIGN KEY (claim_id) REFERENCES claim (claim_id), FOREIGN KEY (role_type_id) REFERENCES role_type (role_type_id), FOREIGN KEY (person_id) REFERENCES person (person_id));
CREATE TABLE IF NOT EXISTS "finding" (finding_id INTEGER PRIMARY KEY AUTOINCREMENT, date TEXT NOT NULL DEFAULT '-0000-00-00-', particulars TEXT NOT NULL DEFAULT '', age TEXT NOT NULL DEFAULT '', person_id INTEGER, event_type_id INTEGER NOT NULL, date_sorter TEXT NOT NULL DEFAULT '0, 0, 0', FOREIGN KEY (person_id) REFERENCES person (person_id), FOREIGN KEY (event_type_id) REFERENCES event_type (event_type_id));
CREATE TABLE IF NOT EXISTS "finding_places" (finding_places_id INTEGER PRIMARY KEY AUTOINCREMENT, finding_id INTEGER UNIQUE, nest0 INTEGER NOT NULL DEFAULT 1, nest1 INTEGER DEFAULT NULL, nest2 INTEGER DEFAULT NULL, nest3 INTEGER DEFAULT NULL, nest4 INTEGER DEFAULT NULL, nest5 INTEGER DEFAULT NULL, nest6 INTEGER DEFAULT NULL, nest7 INTEGER DEFAULT NULL, nest8 INTEGER DEFAULT NULL, FOREIGN KEY (finding_id) REFERENCES finding (finding_id), FOREIGN KEY (nest0) REFERENCES place (place_id), FOREIGN KEY (nest1) REFERENCES place (place_id), FOREIGN KEY (nest2) REFERENCES place (place_id), FOREIGN KEY (nest3) REFERENCES place (place_id), FOREIGN KEY (nest4) REFERENCES place (place_id), FOREIGN KEY (nest5) REFERENCES place (place_id), FOREIGN KEY (nest6) REFERENCES place (place_id), FOREIGN KEY (nest7) REFERENCES place (place_id), FOREIGN KEY (nest8) REFERENCES place (place_id));
CREATE TABLE IF NOT EXISTS "findings_roles" (findings_roles_id INTEGER PRIMARY KEY AUTOINCREMENT, finding_id INTEGER NOT NULL, role_type_id INTEGER NOT NULL, person_id INTEGER DEFAULT NULL, FOREIGN KEY (finding_id) REFERENCES finding (finding_id), FOREIGN KEY (role_type_id) REFERENCES role_type (role_type_id), FOREIGN KEY (person_id) REFERENCES person (person_id));
CREATE TABLE IF NOT EXISTS "name" (name_id INTEGER PRIMARY KEY AUTOINCREMENT, person_id INTEGER NOT NULL, names TEXT NOT NULL, name_type_id INTEGER NOT NULL DEFAULT 18, sort_order TEXT NOT NULL, used_by TEXT, FOREIGN KEY (person_id) REFERENCES person (person_id), FOREIGN KEY (name_type_id) REFERENCES name_type (name_type_id));
INSERT INTO name VALUES(1,1,'',16,'','');
CREATE TABLE IF NOT EXISTS "places_places" (places_places_id INTEGER PRIMARY KEY AUTOINCREMENT, place_id1 INTEGER NOT NULL, place_id2 INTEGER DEFAULT NULL, period TEXT NOT NULL DEFAULT '', FOREIGN KEY (place_id1) REFERENCES place (place_id), FOREIGN KEY (place_id2) REFERENCES place (place_id));
INSERT INTO places_places VALUES(1,1,NULL,'');
CREATE TABLE IF NOT EXISTS "setting" (setting_id INTEGER PRIMARY KEY AUTOINCREMENT, image_male_id INTEGER, image_female_id INTEGER, image_unisex_id INTEGER, image_source_id INTEGER, image_place_id INTEGER, default_image_male_id INTEGER NOT NULL DEFAULT 17, default_image_female_id INTEGER NOT NULL DEFAULT 15, default_image_unisex_id INTEGER NOT NULL DEFAULT 14, default_image_source_id INTEGER NOT NULL DEFAULT 18, default_image_place_id INTEGER NOT NULL DEFAULT 19, FOREIGN KEY (image_male_id) REFERENCES image (image_id), FOREIGN KEY (image_female_id) REFERENCES image (image_id), FOREIGN KEY (image_unisex_id) REFERENCES image (image_id), FOREIGN KEY (image_source_id) REFERENCES image (image_id), FOREIGN KEY (image_place_id) REFERENCES image (image_id));
INSERT INTO setting VALUES(1,NULL,NULL,NULL,NULL,NULL,17,15,14,18,19);
CREATE TABLE IF NOT EXISTS "findings_notes" (findings_notes_id INTEGER PRIMARY KEY AUTOINCREMENT, finding_id INTEGER NOT NULL, note_id INTEGER NOT NULL, topic_order INTEGER NOT NULL DEFAULT 0, FOREIGN KEY (finding_id) REFERENCES finding (finding_id), FOREIGN KEY (note_id) REFERENCES note (note_id));
CREATE TABLE IF NOT EXISTS "note" (note_id INTEGER PRIMARY KEY AUTOINCREMENT, notes TEXT NOT NULL DEFAULT '', private BOOLEAN NOT NULL DEFAULT 0, topic TEXT NOT NULL UNIQUE DEFAULT 'Note 1');
CREATE TABLE chart_type (chart_type_id INTEGER PRIMARY KEY AUTOINCREMENT, chart_types TEXT NOT NULL DEFAULT '');
INSERT INTO chart_type VALUES(1,'descendant');
INSERT INTO chart_type VALUES(2,'ancestor');
INSERT INTO chart_type VALUES(3,'ancestor and descendant');
INSERT INTO chart_type VALUES(4,'relatives');
INSERT INTO chart_type VALUES(5,'fan');
CREATE TABLE contact (contact_id INTEGER PRIMARY KEY AUTOINCREMENT, contact_name TEXT DEFAULT '', email TEXT default '', address TEXT DEFAULT '', phone TEXT DEFAULT '', cell TEXT DEFAULT '', website TEXT DEFAULT '', blog TEXT DEFAULT '', forum TEXT DEFAULT '', forum_handle TEXT DEFAULT '', ancestry_handle TEXT DEFAULT '', familysearch_handle TEXT DEFAULT '', findagrave_handle TEXT DEFAULT '', other1 TEXT DEFAULT '', other2 TEXT DEFAULT '', other3 TEXT DEFAULT '');
CREATE TABLE IF NOT EXISTS "images_elements" (images_elements_id INTEGER PRIMARY KEY AUTOINCREMENT, image_id INTEGER NOT NULL, main_image BOOLEAN NOT NULL DEFAULT 0, person_id INTEGER, place_id INTEGER, citation_id INTEGER, FOREIGN KEY (image_id) REFERENCES image (image_id), FOREIGN KEY (person_id) REFERENCES person (person_id), FOREIGN KEY (place_id) REFERENCES place (place_id), FOREIGN KEY (citation_id) REFERENCES citation (citation_id));
CREATE TABLE links_links (links_links_id INTEGER PRIMARY KEY AUTOINCREMENT, person_id INTEGER, places_places_id INTEGER, name_id INTEGER, source_id INTEGER, citation_id INTEGER, finding_id INTEGER, claim_id INTEGER, project_id INTEGER, to_do_id INTEGER, contact_id INTEGER, image_id INTEGER, note_id INTEGER, role_id INTEGER, repository_id INTEGER, report_id, INTEGER, chart_id INTEGER, media_id INTEGER, FOREIGN KEY (person_id) REFERENCES person (person_id), FOREIGN KEY (places_places_id) REFERENCES places_places (places_places_id), FOREIGN KEY (name_id) REFERENCES name (name_id), FOREIGN KEY (source_id) REFERENCES source (source_id), FOREIGN KEY (citation_id) REFERENCES citation (citation_id), FOREIGN KEY (finding_id) REFERENCES finding (finding_id), FOREIGN KEY (claim_id) REFERENCES claim (claim_id), FOREIGN KEY (project_id) REFERENCES project (project_id), FOREIGN KEY (to_do_id) REFERENCES to_do (to_do_id), FOREIGN KEY (contact_id) REFERENCES contact (contact_id), FOREIGN KEY (image_id) REFERENCES image (image_id), FOREIGN KEY (note_id) REFERENCES note (note_id), FOREIGN KEY (role_id) REFERENCES role (role_id), FOREIGN KEY (repository_id) REFERENCES repository (repository_id), FOREIGN KEY (report_id) REFERENCES report (report_id), FOREIGN KEY (chart_id) REFERENCES chart (chart_id), FOREIGN KEY (media_id) REFERENCES media (media_id));
CREATE TABLE media (media_id INTEGER PRIMARY KEY AUTOINCREMENT, media_name TEXT DEFAULT '', media_type INTEGER, FOREIGN KEY (media_type) REFERENCES media_type (media_type_id));
CREATE TABLE media_type (media_type_id INTEGER PRIMARY KEY AUTOINCREMENT, media_types TEXT NOT NULL DEFAULT '');
INSERT INTO media_type VALUES(1,'sound recording');
INSERT INTO media_type VALUES(2,'video recording');
INSERT INTO media_type VALUES(3,'home movie');
INSERT INTO media_type VALUES(4,'drawing');
INSERT INTO media_type VALUES(5,'painting');
CREATE TABLE project (project_id INTEGER PRIMARY KEY AUTOINCREMENT, projects TEXT NOT NULL DEFAULT '', project_summary TEXT);
CREATE TABLE report (report_id INTEGER PRIMARY KEY AUTOINCREMENT, report_name TEXT NOT NULL DEFAULT '', report_type INTEGER, FOREIGN KEY (report_type) REFERENCES report_type (report_type_id));
CREATE TABLE report_type (report_type_id INTEGER PRIMARY KEY AUTOINCREMENT, report_types TEXT NOT NULL DEFAULT '');
INSERT INTO report_type VALUES(1,'Narrative');
INSERT INTO report_type VALUES(2,'Outline');
INSERT INTO report_type VALUES(3,'Pedigree');
CREATE TABLE repository (repository_id INTEGER PRIMARY KEY AUTOINCREMENT, repository_name TEXT NOT NULL DEFAULT '', contact_name TEXT DEFAULT '', email TEXT default '', address TEXT DEFAULT '', phone TEXT DEFAULT '', cell TEXT DEFAULT '', website TEXT DEFAULT '', blog TEXT DEFAULT '', forum TEXT DEFAULT '', forum_handle TEXT DEFAULT '',  other1 TEXT DEFAULT '', other2 TEXT DEFAULT '', other3 TEXT DEFAULT '');
CREATE TABLE to_do (to_do_id INTEGER PRIMARY KEY AUTOINCREMENT, to_dos TEXT NOT NULL DEFAULT '', priority INTEGER);
CREATE TABLE IF NOT EXISTS "color_scheme" (color_scheme_id INTEGER PRIMARY KEY AUTOINCREMENT, bg TEXT NOT NULL, highlight_bg TEXT NOT NULL, head_bg TEXT NOT NULL, fg TEXT NOT NULL, built_in BOOLEAN NOT NULL DEFAULT 1, hidden BOOLEAN NOT NULL DEFAULT 0);
INSERT INTO color_scheme VALUES(1,'#061d2f','#284b80','#267d82','#71cfd5',1,0);
INSERT INTO color_scheme VALUES(240,'#232931','#393e46','#2E5447','#eeeeee',1,0);
INSERT INTO color_scheme VALUES(241,'#393932','#4d4545','#8d6262','#f1c5c5',1,0);
INSERT INTO color_scheme VALUES(242,'#212121','#323232','#0d7377','#7efee1',1,0);
INSERT INTO color_scheme VALUES(243,'#423030','#605656','gray','lightgray',1,0);
INSERT INTO color_scheme VALUES(244,'#a3e4db','#fed1ef','#72aef7','#333333',1,0);
INSERT INTO color_scheme VALUES(246,'#d3e4cd','#f2ddc1','#e2c2b9','#33282d',1,0);
INSERT INTO color_scheme VALUES(247,'#fff1af','#b4c6a6','#ab937b','#1c150e',1,0);
INSERT INTO color_scheme VALUES(248,'#f3f0d7','#cee5d0','#fed2aa','#1f1913',1,0);
INSERT INTO color_scheme VALUES(249,'#c8e3d4','#f6d7a7','#f6eabe','#1a1814',1,0);
INSERT INTO color_scheme VALUES(250,'#e5dcc3','#c7bea2','#aaa492','#12110f',1,0);
INSERT INTO color_scheme VALUES(251,'#faeee0','#f9e4c8','#d8d0c0','#121110',1,0);
INSERT INTO color_scheme VALUES(252,'#f3f0d7','#cee5d0','#e0c097','#1d2226',1,0);
INSERT INTO color_scheme VALUES(253,'#f3d5c0','#d4b499','#889eaf','#242426',1,0);
INSERT INTO color_scheme VALUES(254,'#ffe3e3','#e4d8dc','#c9ccd5','#21201a',1,0);
INSERT INTO color_scheme VALUES(255,'#feffe2','#f0f0cb','#dad5ab','#1c1a17',1,0);
INSERT INTO color_scheme VALUES(256,'#f4dfd0','#dad0c2','#cdbba7','#1a1615',1,0);
INSERT INTO color_scheme VALUES(257,'#f8e2cf','#f5c6aa','#fcd8d4','#0f1112',1,0);
INSERT INTO color_scheme VALUES(258,'#f1ecc3','#c9d8b6','#90a7b0','#171612',1,0);
INSERT INTO color_scheme VALUES(259,'#e6ddc6','#c3b8a3','#a19882','#1f181b',1,0);
INSERT INTO color_scheme VALUES(260,'#caf7e3','#f6dfeb','#e4bad4','#1c1a16',1,0);
INSERT INTO color_scheme VALUES(261,'#f6e6cb','#e3cdc1','#a0937d','#171a16',1,0);
INSERT INTO color_scheme VALUES(262,'#f8ede3','#bdd2b6','#798777','#171315',1,0);
INSERT INTO color_scheme VALUES(263,'#caf7e3','#f6dfeb','#e4bad4','#141414',1,0);
INSERT INTO color_scheme VALUES(264,'#f9f7cf','#f2dcbb','#bbbbbb','#151617',1,0);
INSERT INTO color_scheme VALUES(265,'#f4f4f2','#e8e8e8','#bbbfca','#170e11',1,0);
INSERT INTO color_scheme VALUES(266,'#d6e5fa','#baabda','#d77fa1','#1a0e12',1,0);
INSERT INTO color_scheme VALUES(268,'#433520','#025955','#00917c','#fde8cd',1,0);
INSERT INTO color_scheme VALUES(269,'#0d335d','#1a508b','#c1a1d3','#fff3e6',1,0);
INSERT INTO color_scheme VALUES(270,'#19456b','#11698e','#16c79a','#f8f1f1',1,0);
INSERT INTO color_scheme VALUES(271,'#424242','#a98b98','#4e3d53','#a6f0c6',1,0);
INSERT INTO color_scheme VALUES(272,'#351f39','#726a95','#485154','#a0c1b8',1,0);
INSERT INTO color_scheme VALUES(273,'#222831','#4f8a8b','#615229','#eeeeee',1,0);
INSERT INTO color_scheme VALUES(274,'#3e3838','#ae7c7c','#365e5a','#e3dada',1,0);
INSERT INTO color_scheme VALUES(276,'#041c32','#04293a','#064663','#ced7db',1,0);
INSERT INTO color_scheme VALUES(277,'#112031','#152d35','#345b63','#d4ecdd',1,0);
INSERT INTO color_scheme VALUES(278,'#334257','#476062','#548ca8','#eeeeee',1,0);
INSERT INTO color_scheme VALUES(279,'#351f39','#726a95','#485154','#a0c1b8',1,0);
INSERT INTO color_scheme VALUES(280,'#382933','#3b5249','#3d5448','#a4b494',1,0);
INSERT INTO color_scheme VALUES(281,'#4d4646','#5b5656','#47544a','#f5eaea',1,0);
INSERT INTO color_scheme VALUES(283,'#33313b','#62374e','#007880','#ccbec5',1,0);
INSERT INTO color_scheme VALUES(284,'#33313b','#3c4f65','#834c69','#e6f5ff',1,0);
INSERT INTO color_scheme VALUES(286,'#2a2438','#352f44','#5c5470','#dbd8e3',1,0);
INSERT INTO color_scheme VALUES(288,'#35483a','#647d73','#7e6373','#d5e0dc',1,0);
INSERT INTO color_scheme VALUES(289,'#35483a','#647d73','#4d444b','#d5e0dc',1,0);
INSERT INTO color_scheme VALUES(290,'#34615f','#4a8a87','#486a8c','#b9ddd9',1,0);
INSERT INTO color_scheme VALUES(291,'#344140','#5a7270','#977d77','#ffffff',1,0);
INSERT INTO color_scheme VALUES(292,'#1e1e1e','#484848','#43523f','#d7d7d7',1,0);
INSERT INTO color_scheme VALUES(293,'#b8a089','#cbbaa9','#ded3c9','#2d241c',1,0);
INSERT INTO color_scheme VALUES(294,'#0C1021','#55606c','#808c9b','white',1,0);
INSERT INTO color_scheme VALUES(295,'#283133','#899ea3','#86a68b','white',1,0);
INSERT INTO color_scheme VALUES(296,'#2F343F','#424242','#212121','#AFB9C6',1,0);
INSERT INTO color_scheme VALUES(297,'#38555f','#507987','#4d598a','#ced6d9',1,0);
INSERT INTO color_scheme VALUES(298,'#151a26','#3d4b6d','#6c8093','#dadee6',1,0);
INSERT INTO color_scheme VALUES(299,'#152028','#232b32','#202945','#d8dee3',1,0);
INSERT INTO color_scheme VALUES(300,'#121212','#606782','#34393b','#99b0bb',1,0);
INSERT INTO color_scheme VALUES(301,'#121212','#403250','#34383d','#d9d5de',1,0);
INSERT INTO color_scheme VALUES(302,'#dbdde8','#b4b8cf','#8087ae','#1c1c21',1,0);
INSERT INTO color_scheme VALUES(303,'#bcd0d3','#97b7bb','#639196','#141b1c',1,0);
CREATE TABLE IF NOT EXISTS "current" (current_id INTEGER PRIMARY KEY AUTOINCREMENT, place_id INTEGER, person_id INTEGER, citation_id INTEGER REFERENCES citation (citation_id), color_scheme_id INTEGER DEFAULT null REFERENCES color_scheme (color_scheme_id), FOREIGN KEY (place_id) REFERENCES place (place_id), FOREIGN KEY (person_id) REFERENCES person (person_id));
INSERT INTO "current" VALUES(1,4,6,9,1);
CREATE TABLE format (format_id INTEGER PRIMARY KEY AUTOINCREMENT, bg TEXT, highlight_bg TEXT, head_bg TEXT, fg TEXT, output_font TEXT, input_font TEXT, font_size INTEGER, default_bg TEXT NOT NULL DEFAULT '#393932', default_highlight_bg TEXT NOT NULL DEFAULT '#4d4545', default_head_bg TEXT NOT NULL DEFAULT '#8d6262', default_fg TEXT NOT NULL DEFAULT '#f1c5c5', default_output_font TEXT NOT NULL DEFAULT 'courier', default_input_font TEXT NOT NULL DEFAULT 'tahoma', default_font_size INTEGER NOT NULL DEFAULT 12);
INSERT INTO format VALUES(1,'#382933','#3b5249','#3d5448','#a4b494','Courier','dejavu sans mono',12,'#061d2f','#284b80','#267d82','#71cfd5','Courier','dejavu sans mono',12);
CREATE TABLE persons_persons (persons_persons_id INTEGER PRIMARY KEY AUTOINCREMENT, person_id1 INTEGER DEFAULT null, person_id2 INTEGER DEFAULT null, FOREIGN KEY (person_id1) REFERENCES person (person_id), FOREIGN KEY (person_id2) REFERENCES person (person_id));
CREATE TABLE IF NOT EXISTS "findings_persons" (findings_persons_id INTEGER PRIMARY KEY AUTOINCREMENT, finding_id INTEGER NOT NULL, age1 TEXT NOT NULL DEFAULT '', kin_type_id1 INTEGER, age2 TEXT NOT NULL DEFAULT '', kin_type_id2 INTEGER, persons_persons_id INTEGER NOT NULL REFERENCES persons_persons (persons_persons_id), FOREIGN KEY (finding_id) REFERENCES finding (finding_id), FOREIGN KEY (kin_type_id1) REFERENCES kin_type (kin_type_id), FOREIGN KEY (kin_type_id2) REFERENCES kin_type (kin_type_id));
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('source',29);
INSERT INTO sqlite_sequence VALUES('image',61);
INSERT INTO sqlite_sequence VALUES('event_type',105);
INSERT INTO sqlite_sequence VALUES('kin_type',124);
INSERT INTO sqlite_sequence VALUES('name_type',25);
INSERT INTO sqlite_sequence VALUES('person',5755);
INSERT INTO sqlite_sequence VALUES('role_type',112);
INSERT INTO sqlite_sequence VALUES('date_format',1);
INSERT INTO sqlite_sequence VALUES('place',906);
INSERT INTO sqlite_sequence VALUES('citation',10);
INSERT INTO sqlite_sequence VALUES('claim',8);
INSERT INTO sqlite_sequence VALUES('claims_findings',5);
INSERT INTO sqlite_sequence VALUES('claims_notes',5);
INSERT INTO sqlite_sequence VALUES('claims_roles',6);
INSERT INTO sqlite_sequence VALUES('finding',656);
INSERT INTO sqlite_sequence VALUES('finding_places',669);
INSERT INTO sqlite_sequence VALUES('findings_roles',241);
INSERT INTO sqlite_sequence VALUES('name',1805);
INSERT INTO sqlite_sequence VALUES('places_places',660);
INSERT INTO sqlite_sequence VALUES('setting',1);
INSERT INTO sqlite_sequence VALUES('chart_type',5);
INSERT INTO sqlite_sequence VALUES('images_elements',756);
INSERT INTO sqlite_sequence VALUES('media_type',5);
INSERT INTO sqlite_sequence VALUES('report_type',3);
INSERT INTO sqlite_sequence VALUES('color_scheme',317);
INSERT INTO sqlite_sequence VALUES('current',1);
INSERT INTO sqlite_sequence VALUES('format',1);
INSERT INTO sqlite_sequence VALUES('persons_persons',41);
INSERT INTO sqlite_sequence VALUES('findings_persons',149);
COMMIT;
