PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE image (image_id INTEGER PRIMARY KEY AUTOINCREMENT, images TEXT UNIQUE NOT NULL, caption TEXT);
CREATE TABLE person (PERSON_ID integer primary key autoincrement, gender TEXT NOT NULL DEFAULT 'unknown');
INSERT INTO person VALUES(1,'unknown');
CREATE TABLE IF NOT EXISTS "date_format" (date_format_id INTEGER PRIMARY KEY AUTOINCREMENT, date_formats TEXT NOT NULL DEFAULT 'alpha_dmy', abt TEXT NOT NULL DEFAULT 'abt', est TEXT NOT NULL DEFAULT 'est', cal TEXT NOT NULL DEFAULT 'calc', bef_aft TEXT NOT NULL DEFAULT 'bef/aft', bc_ad TEXT NOT NULL DEFAULT 'BCE/CE', os_ns TEXT NOT NULL DEFAULT 'OS/NS', span TEXT NOT NULL DEFAULT 'from_to', range TEXT NOT NULL DEFAULT 'btwn_&');
CREATE TABLE IF NOT EXISTS "place" (place_id INTEGER PRIMARY KEY AUTOINCREMENT, places TEXT NOT NULL, latitude TEXT DEFAULT '', longitude TEXT DEFAULT '', cartesian_coordinates TEXT DEFAULT '', township TEXT DEFAULT '', range TEXT DEFAULT '', section TEXT DEFAULT '', legal_subdivision TEXT DEFAULT '', hint TEXT UNIQUE DEFAULT null);
INSERT INTO place VALUES(1,'unknown','','','','','','','',NULL);
CREATE TABLE IF NOT EXISTS "color_scheme" (color_scheme_id INTEGER PRIMARY KEY AUTOINCREMENT, bg TEXT NOT NULL, highlight_bg TEXT NOT NULL, head_bg TEXT NOT NULL, fg TEXT NOT NULL, built_in BOOLEAN NOT NULL DEFAULT 1, hidden BOOLEAN NOT NULL DEFAULT 0);
INSERT INTO color_scheme VALUES(1,'#061d2f','#284b80','#267d82','#71cfd5',1,0);
INSERT INTO color_scheme VALUES(2,'red','magenta','blue','yellow',1,1);
INSERT INTO color_scheme VALUES(240,'#232931','#393e46','#2E5447','#eeeeee',1,0);
INSERT INTO color_scheme VALUES(241,'#393932','#4d4545','#8d6262','#f1c5c5',1,0);
INSERT INTO color_scheme VALUES(242,'#212121','#323232','#0d7377','#7efee1',1,0);
INSERT INTO color_scheme VALUES(243,'#423030','#605656','gray','lightgray',1,0);
INSERT INTO color_scheme VALUES(244,'#a3e4db','#fed1ef','#72aef7','#333333',1,0);
INSERT INTO color_scheme VALUES(245,'#f0ece3','#dfd3c3','#c7b198','#5e5448',1,1);
INSERT INTO color_scheme VALUES(246,'#d3e4cd','#f2ddc1','#e2c2b9','#33282d',1,0);
INSERT INTO color_scheme VALUES(247,'#fff1af','#b4c6a6','#ab937b','#1c150e',1,0);
INSERT INTO color_scheme VALUES(248,'#f3f0d7','#cee5d0','#fed2aa','#1f1913',1,0);
INSERT INTO color_scheme VALUES(249,'#c8e3d4','#f6d7a7','#f6eabe','#1a1814',1,0);
INSERT INTO color_scheme VALUES(250,'#e5dcc3','#c7bea2','#aaa492','#12110f',1,0);
INSERT INTO color_scheme VALUES(251,'#faeee0','#f9e4c8','#d8d0c0','#121110',1,0);
INSERT INTO color_scheme VALUES(252,'#f3f0d7','#cee5d0','#e0c097','#1d2226',1,0);
INSERT INTO color_scheme VALUES(253,'#f3d5c0','#d4b499','#889eaf','#242426',1,0);
INSERT INTO color_scheme VALUES(254,'#ffe3e3','#e4d8dc','#c9ccd5','#21201a',1,0);
INSERT INTO color_scheme VALUES(255,'#feffe2','#f0f0cb','#dad5ab','#1c1a17',1,0);
INSERT INTO color_scheme VALUES(256,'#f4dfd0','#dad0c2','#cdbba7','#1a1615',1,0);
INSERT INTO color_scheme VALUES(257,'#f8e2cf','#f5c6aa','#fcd8d4','#0f1112',1,0);
INSERT INTO color_scheme VALUES(258,'#f1ecc3','#c9d8b6','#90a7b0','#171612',1,0);
INSERT INTO color_scheme VALUES(259,'#e6ddc6','#c3b8a3','#a19882','#1f181b',1,0);
INSERT INTO color_scheme VALUES(260,'#caf7e3','#f6dfeb','#e4bad4','#1c1a16',1,0);
INSERT INTO color_scheme VALUES(261,'#f6e6cb','#e3cdc1','#a0937d','#171a16',1,0);
INSERT INTO color_scheme VALUES(262,'#f8ede3','#bdd2b6','#798777','#171315',1,0);
INSERT INTO color_scheme VALUES(263,'#caf7e3','#f6dfeb','#e4bad4','#141414',1,0);
INSERT INTO color_scheme VALUES(264,'#f9f7cf','#f2dcbb','#bbbbbb','#151617',1,0);
INSERT INTO color_scheme VALUES(265,'#f4f4f2','#e8e8e8','#bbbfca','#170e11',1,0);
INSERT INTO color_scheme VALUES(266,'#d6e5fa','#baabda','#d77fa1','#1a0e12',1,0);
INSERT INTO color_scheme VALUES(267,'#7b6079','#506362','#de8971','#e3d8e2',1,1);
INSERT INTO color_scheme VALUES(268,'#433520','#025955','#00917c','#fde8cd',1,0);
INSERT INTO color_scheme VALUES(269,'#0d335d','#1a508b','#c1a1d3','#fff3e6',1,0);
INSERT INTO color_scheme VALUES(270,'#19456b','#11698e','#16c79a','#f8f1f1',1,0);
INSERT INTO color_scheme VALUES(271,'#424242','#a98b98','#4e3d53','#a6f0c6',1,0);
INSERT INTO color_scheme VALUES(272,'#351f39','#726a95','#485154','#a0c1b8',1,0);
INSERT INTO color_scheme VALUES(273,'#222831','#4f8a8b','#615229','#eeeeee',1,0);
INSERT INTO color_scheme VALUES(274,'#3e3838','#ae7c7c','#365e5a','#e3dada',1,0);
INSERT INTO color_scheme VALUES(275,'#305973','#ef7e56','#787371','#e6dfdc',1,1);
INSERT INTO color_scheme VALUES(276,'#041c32','#04293a','#064663','#ced7db',1,0);
INSERT INTO color_scheme VALUES(277,'#112031','#152d35','#345b63','#d4ecdd',1,0);
INSERT INTO color_scheme VALUES(278,'#334257','#476062','#548ca8','#eeeeee',1,0);
INSERT INTO color_scheme VALUES(279,'#351f39','#726a95','#485154','#a0c1b8',1,0);
INSERT INTO color_scheme VALUES(280,'#382933','#3b5249','#3d5448','#a4b494',1,0);
INSERT INTO color_scheme VALUES(281,'#4d4646','#5b5656','#47544a','#f5eaea',1,0);
INSERT INTO color_scheme VALUES(282,'#222831','#393e46','#d65a31','#eeeeee',1,1);
INSERT INTO color_scheme VALUES(283,'#33313b','#62374e','#007880','#ccbec5',1,0);
INSERT INTO color_scheme VALUES(284,'#33313b','#3c4f65','#834c69','#e6f5ff',1,0);
INSERT INTO color_scheme VALUES(285,'#272121','#363333','#e16428','#f6e9e9',1,1);
INSERT INTO color_scheme VALUES(286,'#2a2438','#352f44','#5c5470','#dbd8e3',1,0);
INSERT INTO color_scheme VALUES(287,'#a0937d','#3a6351','#5f939a','#f2edd7',1,1);
INSERT INTO color_scheme VALUES(288,'#35483a','#647d73','#7e6373','#d5e0dc',1,0);
INSERT INTO color_scheme VALUES(289,'#35483a','#647d73','#4d444b','#d5e0dc',1,0);
INSERT INTO color_scheme VALUES(290,'#34615f','#4a8a87','#486a8c','#b9ddd9',1,0);
INSERT INTO color_scheme VALUES(291,'#344140','#5a7270','#977d77','#ffffff',1,0);
INSERT INTO color_scheme VALUES(292,'#1e1e1e','#484848','#43523f','#d7d7d7',1,0);
INSERT INTO color_scheme VALUES(293,'#b8a089','#cbbaa9','#ded3c9','#2d241c',1,0);
INSERT INTO color_scheme VALUES(294,'#0C1021','#55606c','#808c9b','white',1,0);
INSERT INTO color_scheme VALUES(295,'#283133','#899ea3','#86a68b','white',1,0);
INSERT INTO color_scheme VALUES(296,'#2F343F','#424242','#212121','#AFB9C6',1,0);
INSERT INTO color_scheme VALUES(297,'#38555f','#507987','#4d598a','#ced6d9',1,0);
INSERT INTO color_scheme VALUES(298,'#151a26','#3d4b6d','#6c8093','#dadee6',1,0);
INSERT INTO color_scheme VALUES(299,'#152028','#232b32','#202945','#d8dee3',1,0);
INSERT INTO color_scheme VALUES(300,'#121212','#606782','#34393b','#99b0bb',1,0);
INSERT INTO color_scheme VALUES(301,'#121212','#403250','#34383d','#d9d5de',1,0);
INSERT INTO color_scheme VALUES(302,'#dbdde8','#b4b8cf','#8087ae','#1c1c21',1,0);
INSERT INTO color_scheme VALUES(303,'#bcd0d3','#97b7bb','#639196','#141b1c',1,0);
INSERT INTO color_scheme VALUES(314,'#f0ece3','#dfd3c3','#c7b198','#363636',0,0);
INSERT INTO color_scheme VALUES(315,'#a0937d','#3a6351','#5f939a','#f3f3f3',0,0);
INSERT INTO color_scheme VALUES(317,'#34615f','#4a8a87','#486a8c','#faeefb',0,0);
CREATE TABLE IF NOT EXISTS "citation" (citation_id INTEGER PRIMARY KEY AUTOINCREMENT, source_id INTEGER NOT NULL, citations TEXT, FOREIGN KEY (source_id) REFERENCES source (source_id));
CREATE TABLE IF NOT EXISTS "claims_findings" (claims_findings_id INTEGER PRIMARY KEY AUTOINCREMENT, claim_id INTEGER NOT NULL, finding_id INTEGER NOT NULL, FOREIGN KEY (claim_id) REFERENCES claim (claim_id), FOREIGN KEY (finding_id) REFERENCES finding (finding_id));
CREATE TABLE IF NOT EXISTS "claims_notes" (claims_notes_id INTEGER PRIMARY KEY AUTOINCREMENT, claim_id INTEGER NOT NULL, note_id INTEGER NOT NULL, FOREIGN KEY (claim_id) REFERENCES claim (claim_id), FOREIGN KEY (note_id) REFERENCES note (note_id));
CREATE TABLE IF NOT EXISTS "claims_roles" (claims_roles_id INTEGER PRIMARY KEY AUTOINCREMENT, claim_id INTEGER NOT NULL, role_type_id INTEGER NOT NULL, person_id INTEGER NOT NULL, FOREIGN KEY (claim_id) REFERENCES claim (claim_id), FOREIGN KEY (role_type_id) REFERENCES role_type (role_type_id), FOREIGN KEY (person_id) REFERENCES person (person_id));
CREATE TABLE IF NOT EXISTS "current" (current_id INTEGER PRIMARY KEY AUTOINCREMENT, place_id INTEGER, person_id INTEGER, citation_id INTEGER REFERENCES citation (citation_id), color_scheme_id INTEGER DEFAULT null REFERENCES color_scheme (color_scheme_id), FOREIGN KEY (place_id) REFERENCES place (place_id), FOREIGN KEY (person_id) REFERENCES person (person_id));
INSERT INTO "current" VALUES(1,NULL,1,NULL,1);
CREATE TABLE IF NOT EXISTS "findings_roles" (findings_roles_id INTEGER PRIMARY KEY AUTOINCREMENT, finding_id INTEGER NOT NULL, role_type_id INTEGER NOT NULL, person_id INTEGER DEFAULT NULL, FOREIGN KEY (finding_id) REFERENCES finding (finding_id), FOREIGN KEY (role_type_id) REFERENCES role_type (role_type_id), FOREIGN KEY (person_id) REFERENCES person (person_id));
CREATE TABLE IF NOT EXISTS "places_places" (places_places_id INTEGER PRIMARY KEY AUTOINCREMENT, place_id1 INTEGER NOT NULL, place_id2 INTEGER DEFAULT NULL, period TEXT NOT NULL DEFAULT '', FOREIGN KEY (place_id1) REFERENCES place (place_id), FOREIGN KEY (place_id2) REFERENCES place (place_id));
INSERT INTO places_places VALUES(1,1,NULL,'');
CREATE TABLE IF NOT EXISTS "setting" (setting_id INTEGER PRIMARY KEY AUTOINCREMENT, image_male_id INTEGER, image_female_id INTEGER, image_unisex_id INTEGER, image_source_id INTEGER, image_place_id INTEGER, default_image_male_id INTEGER NOT NULL DEFAULT 17, default_image_female_id INTEGER NOT NULL DEFAULT 15, default_image_unisex_id INTEGER NOT NULL DEFAULT 14, default_image_source_id INTEGER NOT NULL DEFAULT 18, default_image_place_id INTEGER NOT NULL DEFAULT 19, FOREIGN KEY (image_male_id) REFERENCES image (image_id), FOREIGN KEY (image_female_id) REFERENCES image (image_id), FOREIGN KEY (image_unisex_id) REFERENCES image (image_id), FOREIGN KEY (image_source_id) REFERENCES image (image_id), FOREIGN KEY (image_place_id) REFERENCES image (image_id));
CREATE TABLE IF NOT EXISTS "findings_notes" (findings_notes_id INTEGER PRIMARY KEY AUTOINCREMENT, finding_id INTEGER NOT NULL, note_id INTEGER NOT NULL, topic_order INTEGER NOT NULL DEFAULT 0, FOREIGN KEY (finding_id) REFERENCES finding (finding_id), FOREIGN KEY (note_id) REFERENCES note (note_id));
CREATE TABLE IF NOT EXISTS "note" (note_id INTEGER PRIMARY KEY AUTOINCREMENT, notes TEXT NOT NULL DEFAULT '', private BOOLEAN NOT NULL DEFAULT 0, topic TEXT NOT NULL UNIQUE DEFAULT 'Note 1');
CREATE TABLE report_type (report_type_id INTEGER PRIMARY KEY AUTOINCREMENT, report_types TEXT NOT NULL DEFAULT '');
CREATE TABLE media_type (media_type_id INTEGER PRIMARY KEY AUTOINCREMENT, media_types TEXT NOT NULL DEFAULT '');
CREATE TABLE chart_type (chart_type_id INTEGER PRIMARY KEY AUTOINCREMENT, chart_types TEXT NOT NULL DEFAULT '');
CREATE TABLE project (project_id INTEGER PRIMARY KEY AUTOINCREMENT, projects TEXT NOT NULL DEFAULT '', project_summary TEXT);
CREATE TABLE to_do (to_do_id INTEGER PRIMARY KEY AUTOINCREMENT, to_dos TEXT NOT NULL DEFAULT '', priority INTEGER);
CREATE TABLE report (report_id INTEGER PRIMARY KEY AUTOINCREMENT, report_name TEXT NOT NULL DEFAULT '', report_type INTEGER, FOREIGN KEY (report_type) REFERENCES report_type (report_type_id));
CREATE TABLE media (media_id INTEGER PRIMARY KEY AUTOINCREMENT, media_name TEXT DEFAULT '', media_type INTEGER, FOREIGN KEY (media_type) REFERENCES media_type (media_type_id));
CREATE TABLE IF NOT EXISTS "images_elements" (images_elements_id INTEGER PRIMARY KEY AUTOINCREMENT, image_id INTEGER NOT NULL, main_image BOOLEAN NOT NULL DEFAULT 0, person_id INTEGER, place_id INTEGER, citation_id INTEGER, FOREIGN KEY (image_id) REFERENCES image (image_id), FOREIGN KEY (person_id) REFERENCES person (person_id), FOREIGN KEY (place_id) REFERENCES place (place_id), FOREIGN KEY (citation_id) REFERENCES citation (citation_id));
CREATE TABLE links_links (links_links_id INTEGER PRIMARY KEY AUTOINCREMENT, person_id INTEGER, places_places_id INTEGER, name_id INTEGER, source_id INTEGER, citation_id INTEGER, finding_id INTEGER, claim_id INTEGER, project_id INTEGER, to_do_id INTEGER, contact_id INTEGER, image_id INTEGER, note_id INTEGER, role_id INTEGER, repository_id INTEGER, report_id, INTEGER, chart_id INTEGER, media_id INTEGER, FOREIGN KEY (person_id) REFERENCES person (person_id), FOREIGN KEY (places_places_id) REFERENCES places_places (places_places_id), FOREIGN KEY (name_id) REFERENCES name (name_id), FOREIGN KEY (source_id) REFERENCES source (source_id), FOREIGN KEY (citation_id) REFERENCES citation (citation_id), FOREIGN KEY (finding_id) REFERENCES finding (finding_id), FOREIGN KEY (claim_id) REFERENCES claim (claim_id), FOREIGN KEY (project_id) REFERENCES project (project_id), FOREIGN KEY (to_do_id) REFERENCES to_do (to_do_id), FOREIGN KEY (contact_id) REFERENCES contact (contact_id), FOREIGN KEY (image_id) REFERENCES image (image_id), FOREIGN KEY (note_id) REFERENCES note (note_id), FOREIGN KEY (role_id) REFERENCES role (role_id), FOREIGN KEY (repository_id) REFERENCES repository (repository_id), FOREIGN KEY (report_id) REFERENCES report (report_id), FOREIGN KEY (chart_id) REFERENCES chart (chart_id), FOREIGN KEY (media_id) REFERENCES media (media_id));
CREATE TABLE IF NOT EXISTS "name" (name_id INTEGER PRIMARY KEY AUTOINCREMENT, person_id INTEGER NOT NULL, names TEXT NOT NULL, name_type_id INTEGER NOT NULL DEFAULT 18, sort_order TEXT NOT NULL, used_by TEXT NOT NULL DEFAULT '', FOREIGN KEY (person_id) REFERENCES person (person_id), FOREIGN KEY (name_type_id) REFERENCES name_type (name_type_id));
INSERT INTO name VALUES(1,1,'person #1',24,'person #1','');
CREATE TABLE IF NOT EXISTS "finding" (finding_id INTEGER PRIMARY KEY AUTOINCREMENT, date TEXT NOT NULL DEFAULT '-0000-00-00-------', particulars TEXT NOT NULL DEFAULT '', age TEXT NOT NULL DEFAULT '', person_id INTEGER DEFAULT null, event_type_id INTEGER NOT NULL, date_sorter TEXT NOT NULL DEFAULT '0, 0, 0', age1 TEXT NOT NULL DEFAULT '', kin_type_id1 INTEGER, age2 TEXT NOT NULL DEFAULT '', kin_type_id2 INTEGER, person_id1 INTEGER DEFAULT null, person_id2 INTEGER DEFAULT null, nest0 INTEGER NOT NULL DEFAULT 1, nest1 INTEGER DEFAULT NULL, nest2 INTEGER DEFAULT NULL, nest3 INTEGER DEFAULT NULL, nest4 INTEGER DEFAULT NULL, nest5 INTEGER DEFAULT NULL, nest6 INTEGER DEFAULT NULL, nest7 INTEGER DEFAULT NULL, nest8 INTEGER DEFAULT NULL, FOREIGN KEY (person_id) REFERENCES person (person_id), FOREIGN KEY (event_type_id) REFERENCES event_type (event_type_id), FOREIGN KEY (kin_type_id1) REFERENCES kin_type (kin_type_id), FOREIGN KEY (kin_type_id2) REFERENCES kin_type (kin_type_id), FOREIGN KEY (person_id1) REFERENCES person (person_id), FOREIGN KEY (person_id2) REFERENCES person (person_id), FOREIGN KEY (nest0) REFERENCES place (place_id), FOREIGN KEY (nest1) REFERENCES place (place_id), FOREIGN KEY (nest2) REFERENCES place (place_id), FOREIGN KEY (nest3) REFERENCES place (place_id), FOREIGN KEY (nest4) REFERENCES place (place_id), FOREIGN KEY (nest5) REFERENCES place (place_id), FOREIGN KEY (nest6) REFERENCES place (place_id), FOREIGN KEY (nest7) REFERENCES place (place_id), FOREIGN KEY (nest8) REFERENCES place (place_id));
INSERT INTO finding VALUES(1,'-0000-00-00-------','','',1,1,'0, 0, 0','',NULL,'',NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
CREATE TABLE IF NOT EXISTS "format" (format_id INTEGER PRIMARY KEY AUTOINCREMENT, output_font TEXT, input_font TEXT, font_size INTEGER, default_output_font TEXT NOT NULL DEFAULT 'courier', default_input_font TEXT NOT NULL DEFAULT 'tahoma', default_font_size INTEGER NOT NULL DEFAULT 12);
INSERT INTO format VALUES(1,'courier','dejavu sans mono',12,'courier','dejavu sans mono',12);
CREATE TABLE role_type (
       role_type_id INTEGER PRIMARY KEY AUTOINCREMENT, 
       role_types TEXT UNIQUE NOT NULL, built_in BOOLEAN NOT NULL DEFAULT 0, hidden BOOLEAN NOT NULL DEFAULT 0);
INSERT INTO role_type VALUES(1,'religious officer',1,0);
INSERT INTO role_type VALUES(2,'justice of the peace',1,0);
INSERT INTO role_type VALUES(3,'arresting officer',1,0);
INSERT INTO role_type VALUES(4,'supervisor',1,0);
INSERT INTO role_type VALUES(5,'employer',1,0);
INSERT INTO role_type VALUES(6,'midwife',1,0);
INSERT INTO role_type VALUES(7,'bridesmaid',1,0);
INSERT INTO role_type VALUES(8,'best man',1,0);
INSERT INTO role_type VALUES(9,'bible bearer',1,0);
INSERT INTO role_type VALUES(10,'flower girl',1,0);
INSERT INTO role_type VALUES(11,'witness',1,0);
INSERT INTO role_type VALUES(12,'employee',1,0);
INSERT INTO role_type VALUES(13,'assistant',1,0);
INSERT INTO role_type VALUES(14,'roommate',1,0);
INSERT INTO role_type VALUES(15,'landlady',1,0);
INSERT INTO role_type VALUES(16,'landlord',1,0);
INSERT INTO role_type VALUES(17,'unknown',1,0);
INSERT INTO role_type VALUES(18,'foster parent',1,0);
INSERT INTO role_type VALUES(19,'makeup artist',0,0);
INSERT INTO role_type VALUES(20,'financier',1,0);
INSERT INTO role_type VALUES(21,'florist',0,0);
INSERT INTO role_type VALUES(22,'usher',0,0);
INSERT INTO role_type VALUES(23,'photographer',0,0);
INSERT INTO role_type VALUES(24,'bartender',0,0);
INSERT INTO role_type VALUES(25,'bodyguard',0,0);
INSERT INTO role_type VALUES(26,'adoptive parent',1,0);
INSERT INTO role_type VALUES(27,'hairdresser',0,0);
INSERT INTO role_type VALUES(28,'chauffeur',1,0);
INSERT INTO role_type VALUES(29,'treasurer',1,0);
INSERT INTO role_type VALUES(30,'trainer',0,0);
INSERT INTO role_type VALUES(31,'secretary',1,0);
INSERT INTO role_type VALUES(32,'navigator',0,0);
INSERT INTO role_type VALUES(39,'neighbor',1,0);
INSERT INTO role_type VALUES(40,'maid',1,0);
INSERT INTO role_type VALUES(41,'pilot',0,0);
INSERT INTO role_type VALUES(44,'mining partner',1,0);
INSERT INTO role_type VALUES(47,'legal guardian',1,0);
INSERT INTO role_type VALUES(55,'other',1,0);
INSERT INTO role_type VALUES(87,'interior decorator',0,0);
INSERT INTO role_type VALUES(88,'executioner',0,0);
INSERT INTO role_type VALUES(90,'driver',1,0);
INSERT INTO role_type VALUES(96,'host',1,0);
INSERT INTO role_type VALUES(97,'hostess',1,0);
INSERT INTO role_type VALUES(99,'farm hand',1,0);
INSERT INTO role_type VALUES(100,'ranch hand',1,0);
INSERT INTO role_type VALUES(103,'junior partner',1,0);
INSERT INTO role_type VALUES(114,'butler',0,0);
INSERT INTO role_type VALUES(115,'boarder',0,0);
INSERT INTO role_type VALUES(116,'chef',0,0);
CREATE TABLE event_type (event_type_id INTEGER PRIMARY KEY AUTOINCREMENT, event_types TEXT UNIQUE NOT NULL, built_in BOOLEAN NOT NULL DEFAULT 0, hidden BOOLEAN NOT NULL DEFAULT 0, couple BOOLEAN NOT NULL DEFAULT 0, after_death BOOLEAN NOT NULL DEFAULT 0, marital BOOLEAN NOT NULL DEFAULT 0);
INSERT INTO event_type VALUES(1,'birth',1,0,0,0,0);
INSERT INTO event_type VALUES(2,'marriage',1,0,1,0,1);
INSERT INTO event_type VALUES(3,'illness',1,0,0,0,0);
INSERT INTO event_type VALUES(4,'death',1,0,0,0,0);
INSERT INTO event_type VALUES(5,'burial',1,0,0,1,0);
INSERT INTO event_type VALUES(6,'occupation',1,0,0,0,0);
INSERT INTO event_type VALUES(7,'imprisonment',1,0,0,0,0);
INSERT INTO event_type VALUES(8,'deportation',1,0,0,0,0);
INSERT INTO event_type VALUES(9,'invention',1,0,0,0,0);
INSERT INTO event_type VALUES(10,'religious conversion',1,0,0,0,0);
INSERT INTO event_type VALUES(11,'wedding',1,0,1,0,1);
INSERT INTO event_type VALUES(12,'ran away from home',1,0,0,0,0);
INSERT INTO event_type VALUES(13,'residence',1,0,0,0,0);
INSERT INTO event_type VALUES(14,'autopsy',1,0,0,1,0);
INSERT INTO event_type VALUES(15,'divorce',1,0,1,0,1);
INSERT INTO event_type VALUES(16,'engagement',1,0,1,0,0);
INSERT INTO event_type VALUES(17,'annulment',1,0,1,0,1);
INSERT INTO event_type VALUES(18,'separation',1,0,1,0,1);
INSERT INTO event_type VALUES(19,'eye color',1,0,0,0,0);
INSERT INTO event_type VALUES(20,'hair color',1,0,0,0,0);
INSERT INTO event_type VALUES(21,'height',1,0,0,0,0);
INSERT INTO event_type VALUES(22,'weight',1,0,0,0,0);
INSERT INTO event_type VALUES(23,'build',1,0,0,0,0);
INSERT INTO event_type VALUES(24,'complexion',1,0,0,0,0);
INSERT INTO event_type VALUES(25,'race',1,0,0,0,0);
INSERT INTO event_type VALUES(26,'ethnic origin',1,0,0,0,0);
INSERT INTO event_type VALUES(27,'marks, scars',1,0,0,0,0);
INSERT INTO event_type VALUES(28,'disability',1,0,0,0,0);
INSERT INTO event_type VALUES(29,'condition',1,0,0,0,0);
INSERT INTO event_type VALUES(30,'religion',1,0,0,0,0);
INSERT INTO event_type VALUES(31,'career',1,0,0,0,0);
INSERT INTO event_type VALUES(32,'number of children, total',1,0,0,0,0);
INSERT INTO event_type VALUES(33,'number of children, living',1,0,0,0,0);
INSERT INTO event_type VALUES(34,'marital status',1,0,0,0,0);
INSERT INTO event_type VALUES(35,'political affiliation',1,0,0,0,0);
INSERT INTO event_type VALUES(36,'special talent',1,0,0,0,0);
INSERT INTO event_type VALUES(37,'hobby',1,0,0,0,0);
INSERT INTO event_type VALUES(38,'able to read',1,0,0,0,0);
INSERT INTO event_type VALUES(39,'able to write',1,0,0,0,0);
INSERT INTO event_type VALUES(40,'first language',1,0,0,0,0);
INSERT INTO event_type VALUES(41,'nationality',1,0,0,0,0);
INSERT INTO event_type VALUES(42,'education level',1,0,0,0,0);
INSERT INTO event_type VALUES(43,'draft registration',1,0,0,0,0);
INSERT INTO event_type VALUES(44,'legal problem',1,0,0,0,0);
INSERT INTO event_type VALUES(45,'tobacco use',1,1,0,0,0);
INSERT INTO event_type VALUES(46,'alcohol use',1,1,0,0,0);
INSERT INTO event_type VALUES(47,'drug problem',1,1,0,0,0);
INSERT INTO event_type VALUES(48,'guardianship',1,0,0,0,0);
INSERT INTO event_type VALUES(49,'inquest',1,0,0,1,0);
INSERT INTO event_type VALUES(50,'relationship',1,0,1,0,0);
INSERT INTO event_type VALUES(53,'jury duty',1,0,0,0,0);
INSERT INTO event_type VALUES(54,'baptism',1,0,0,0,0);
INSERT INTO event_type VALUES(55,'excommunication',1,0,0,0,0);
INSERT INTO event_type VALUES(56,'betrothal',1,0,1,0,0);
INSERT INTO event_type VALUES(57,'resignation',1,0,0,0,0);
INSERT INTO event_type VALUES(58,'naturalization',1,0,0,0,0);
INSERT INTO event_type VALUES(59,'marriage license',1,0,1,0,1);
INSERT INTO event_type VALUES(60,'christening',1,0,0,0,0);
INSERT INTO event_type VALUES(61,'confirmation',1,0,0,0,0);
INSERT INTO event_type VALUES(62,'cremation',1,0,0,1,0);
INSERT INTO event_type VALUES(63,'will',1,0,0,0,0);
INSERT INTO event_type VALUES(64,'retirement',1,0,0,0,0);
INSERT INTO event_type VALUES(65,'ordination',1,0,0,0,0);
INSERT INTO event_type VALUES(66,'graduation',1,0,0,0,0);
INSERT INTO event_type VALUES(67,'emigration',1,0,0,0,0);
INSERT INTO event_type VALUES(68,'probate',1,0,0,1,0);
INSERT INTO event_type VALUES(69,'enrollment',1,0,0,0,0);
INSERT INTO event_type VALUES(70,'execution',1,0,0,0,0);
INSERT INTO event_type VALUES(71,'employment',1,0,0,0,0);
INSERT INTO event_type VALUES(72,'land grant',1,0,0,0,0);
INSERT INTO event_type VALUES(73,'name change',1,0,0,0,0);
INSERT INTO event_type VALUES(74,'land purchase',1,0,0,0,0);
INSERT INTO event_type VALUES(75,'land sale',1,0,0,0,0);
INSERT INTO event_type VALUES(76,'military induction',1,0,0,0,0);
INSERT INTO event_type VALUES(77,'military enlistment',1,0,0,0,0);
INSERT INTO event_type VALUES(78,'military discharge',1,0,0,0,0);
INSERT INTO event_type VALUES(79,'military promotion',1,0,0,0,0);
INSERT INTO event_type VALUES(80,'military service',1,0,0,0,0);
INSERT INTO event_type VALUES(81,'marriage banns',1,0,1,0,0);
INSERT INTO event_type VALUES(82,'missing in action',1,0,0,0,0);
INSERT INTO event_type VALUES(83,'adoption',1,0,0,0,0);
INSERT INTO event_type VALUES(84,'reburial',1,0,0,1,0);
INSERT INTO event_type VALUES(85,'filing for divorce',1,0,1,0,1);
INSERT INTO event_type VALUES(86,'reading of the will',1,0,0,1,0);
INSERT INTO event_type VALUES(87,'exhumation',1,0,0,1,0);
INSERT INTO event_type VALUES(88,'funeral',1,0,0,1,0);
INSERT INTO event_type VALUES(89,'celebration of life',1,0,0,1,0);
INSERT INTO event_type VALUES(90,'partnership',1,0,1,0,1);
INSERT INTO event_type VALUES(91,'natural disaster',1,0,0,0,0);
INSERT INTO event_type VALUES(93,'anniversary celebration',1,0,1,0,1);
INSERT INTO event_type VALUES(95,'fosterage',1,0,0,0,0);
INSERT INTO event_type VALUES(96,'posthumous offspring',1,0,0,1,0);
INSERT INTO event_type VALUES(97,'acceleration',0,0,0,0,0);
INSERT INTO event_type VALUES(98,'marriage contract',1,0,1,0,1);
INSERT INTO event_type VALUES(99,'reunion',0,0,0,0,0);
INSERT INTO event_type VALUES(100,'scattering of ashes',1,0,0,1,0);
INSERT INTO event_type VALUES(101,'inurnment',1,0,0,1,0);
INSERT INTO event_type VALUES(102,'cohabitation',1,0,1,0,1);
INSERT INTO event_type VALUES(103,'living together',1,0,1,0,1);
INSERT INTO event_type VALUES(104,'wedding anniversary',1,0,1,0,1);
INSERT INTO event_type VALUES(105,'shacking up',1,1,1,0,1);
CREATE TABLE name_type (name_type_id INTEGER PRIMARY KEY AUTOINCREMENT, name_types TEXT UNIQUE DEFAULT '', hierarchy INTEGER DEFAULT 999);
INSERT INTO name_type VALUES(1,'birth name',0);
INSERT INTO name_type VALUES(2,'also known as',3);
INSERT INTO name_type VALUES(3,'pseudonym',6);
INSERT INTO name_type VALUES(4,'ID number',16);
INSERT INTO name_type VALUES(5,'adoptive name',2);
INSERT INTO name_type VALUES(6,'married name',4);
INSERT INTO name_type VALUES(7,'handle',17);
INSERT INTO name_type VALUES(8,'alternate spelling',14);
INSERT INTO name_type VALUES(9,'mis-spelling',15);
INSERT INTO name_type VALUES(10,'legally changed name',5);
INSERT INTO name_type VALUES(11,'stage name',8);
INSERT INTO name_type VALUES(12,'nickname',9);
INSERT INTO name_type VALUES(13,'call name',10);
INSERT INTO name_type VALUES(14,'official name',11);
INSERT INTO name_type VALUES(15,'anglicized name',12);
INSERT INTO name_type VALUES(16,'unknown name',22);
INSERT INTO name_type VALUES(17,'religious order name',13);
INSERT INTO name_type VALUES(18,'other name type',19);
INSERT INTO name_type VALUES(19,'code name',18);
INSERT INTO name_type VALUES(20,'pen name',7);
INSERT INTO name_type VALUES(21,'given name',21);
INSERT INTO name_type VALUES(22,'reference name',1);
INSERT INTO name_type VALUES(23,'surname',20);
INSERT INTO name_type VALUES(24,'placeholder for name',23);
CREATE TABLE kin_type (kin_type_id INTEGER PRIMARY KEY AUTOINCREMENT, kin_types TEXT UNIQUE NOT NULL, kin_code TEXT NOT NULL, hidden BOOLEAN NOT NULL DEFAULT 0);
INSERT INTO kin_type VALUES(1,'father','B',0);
INSERT INTO kin_type VALUES(2,'mother','B',0);
INSERT INTO kin_type VALUES(3,'parent','B',1);
INSERT INTO kin_type VALUES(4,'son','E',0);
INSERT INTO kin_type VALUES(5,'daughter','E',0);
INSERT INTO kin_type VALUES(6,'child','E',0);
INSERT INTO kin_type VALUES(7,'husband','D',0);
INSERT INTO kin_type VALUES(8,'wife','D',0);
INSERT INTO kin_type VALUES(9,'spouse','D',0);
INSERT INTO kin_type VALUES(10,'mate','D',0);
INSERT INTO kin_type VALUES(11,'brother','C',0);
INSERT INTO kin_type VALUES(12,'sister','C',0);
INSERT INTO kin_type VALUES(13,'sibling','C',0);
INSERT INTO kin_type VALUES(14,'partner','D',0);
INSERT INTO kin_type VALUES(15,'common-law spouse','D',0);
INSERT INTO kin_type VALUES(16,'fiance','D',0);
INSERT INTO kin_type VALUES(17,'fiancee','D',0);
INSERT INTO kin_type VALUES(18,'boyfriend','D',0);
INSERT INTO kin_type VALUES(19,'girlfriend','D',0);
INSERT INTO kin_type VALUES(20,'lady friend','D',0);
INSERT INTO kin_type VALUES(21,'lover','D',1);
INSERT INTO kin_type VALUES(22,'mistress','D',0);
INSERT INTO kin_type VALUES(23,'betrothed','D',0);
INSERT INTO kin_type VALUES(24,'groom','D',0);
INSERT INTO kin_type VALUES(25,'bride','D',0);
INSERT INTO kin_type VALUES(26,'biological parent','B',1);
INSERT INTO kin_type VALUES(27,'biological father','B',1);
INSERT INTO kin_type VALUES(28,'biological mother','B',1);
INSERT INTO kin_type VALUES(110,'adoptive parent','B',0);
INSERT INTO kin_type VALUES(111,'adoptive father','B',0);
INSERT INTO kin_type VALUES(112,'adoptive mother','B',0);
INSERT INTO kin_type VALUES(120,'foster parent','B',0);
INSERT INTO kin_type VALUES(121,'foster father','B',0);
INSERT INTO kin_type VALUES(122,'foster mother','B',0);
INSERT INTO kin_type VALUES(128,'generic_partner1','D',0);
INSERT INTO kin_type VALUES(129,'generic_partner2','D',0);
INSERT INTO kin_type VALUES(130,'guardian','B',0);
INSERT INTO kin_type VALUES(131,'legal guardian','B',0);
CREATE TABLE sources_repositories (sources_repositories_id INTEGER PRIMARY KEY AUTOINCREMENT, source_id INTEGER NOT NULL, repository_id INTEGER NOT NULL, FOREIGN KEY (source_id) REFERENCES source (source_id), FOREIGN KEY (repository_id) REFERENCES repository (repository_id));
CREATE TABLE claims_citations (claims_citations_id INTEGER PRIMARY KEY AUTOINCREMENT, claim_id INTEGER NOT NULL, citation_id NOT NULL, FOREIGN KEY (claim_id) REFERENCES claim (claim_id), FOREIGN KEY (citation_id) REFERENCES citation (citation_id));
CREATE TABLE IF NOT EXISTS "claim" (claim_id INTEGER PRIMARY KEY AUTOINCREMENT, person_id INTEGER, event_type_id INTEGER, date TEXT NOT NULL DEFAULT '-0000-00-00-------', particulars TEXT NOT NULL DEFAULT '', age TEXT NOT NULL DEFAULT '', name_id INTEGER, surety FLOAT DEFAULT 3.0, nest0 INTEGER NOT NULL DEFAULT 1 REFERENCES place (place_id), nest1 INTEGER DEFAULT NULL REFERENCES place (place_id), nest2 INTEGER DEFAULT NULL REFERENCES place (place_id), nest3 INTEGER DEFAULT NULL REFERENCES place (place_id), nest4 INTEGER DEFAULT NULL REFERENCES place (place_id), nest5 INTEGER DEFAULT NULL REFERENCES place (place_id), nest6 INTEGER DEFAULT NULL REFERENCES place (place_id), nest7 INTEGER DEFAULT NULL REFERENCES place (place_id), nest8 INTEGER DEFAULT NULL REFERENCES place (place_id), FOREIGN KEY (person_id) REFERENCES person (person_id), FOREIGN KEY (event_type_id) REFERENCES event_type (event_type_id), FOREIGN KEY (name_id) REFERENCES name (name_id));
INSERT INTO claim VALUES(1,1,6,'1878','','32',4,1.5,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO claim VALUES(2,1,10,'Jan 1878','why not','34',5,4.2999999999999998223,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO claim VALUES(3,1,7,'-0000-00-00-------','whatever','35',6,5.0,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO claim VALUES(4,1,6,'1890','odd jobs','92',7,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO claim VALUES(5,1,2,'1860','','57',7,3.0,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO claim VALUES(6,1,3,'1861','','58',7,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO claim VALUES(7,1,3,'1861','','58',7,4.2000000000000001776,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO claim VALUES(8,1,6,'1900','carpenter','52',6,3.2000000000000001776,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
CREATE TABLE IF NOT EXISTS "contact" (contact_id INTEGER PRIMARY KEY AUTOINCREMENT, contact_name TEXT NOT NULL DEFAULT '', position TEXT NOT NULL DEFAULT '', company TEXT NOT NULL DEFAULT '', email TEXT NOT NULL default '', address TEXT NOT NULL DEFAULT '', phone TEXT NOT NULL DEFAULT '', cell TEXT NOT NULL DEFAULT '', website TEXT NOT NULL DEFAULT '', blog TEXT NOT NULL DEFAULT '', forum TEXT NOT NULL DEFAULT '', forum_handle TEXT NOT NULL DEFAULT '', ancestry_handle TEXT NOT NULL DEFAULT '', familysearch_handle TEXT NOT NULL DEFAULT '', findagrave_handle TEXT NOT NULL DEFAULT '', repository_id INTEGER, note_id INTEGER, dogs_name TEXT NOT NULL DEFAULT '', FOREIGN KEY (note_id) REFERENCES note (note_id), FOREIGN KEY (repository_id) REFERENCES repository (repository_id));
CREATE TABLE IF NOT EXISTS "source" (source_id INTEGER PRIMARY KEY AUTOINCREMENT, sources TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "repository" (repository_id INTEGER PRIMARY KEY AUTOINCREMENT, repository_name TEXT NOT NULL DEFAULT '');
CREATE TABLE date_change (date_change_id INTEGER PRIMARY KEY AUTOINCREMENT, date_changes TEXT NOT NULL, time_changes TEXT DEFAULT '', person_id INTEGER, source_id INTEGER, citation_id INTEGER, place_id INTEGER, note_id INTEGER, family_pointer TEXT DEFAULT null, FOREIGN KEY (person_id) REFERENCES person (person_id), FOREIGN KEY (source_id) REFERENCES source (source_id), FOREIGN KEY (place_id) REFERENCES place (place_id), FOREIGN KEY (note_id) REFERENCES note (note_id), FOREIGN KEY (citation_id) REFERENCES citation (citation_id));
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('person',1);
INSERT INTO sqlite_sequence VALUES('finding',1);
INSERT INTO sqlite_sequence VALUES('role_type',116);
INSERT INTO sqlite_sequence VALUES('event_type',105);
INSERT INTO sqlite_sequence VALUES('name_type',24);
INSERT INTO sqlite_sequence VALUES('kin_type',131);
INSERT INTO sqlite_sequence VALUES('name',1);
INSERT INTO sqlite_sequence VALUES('current',1);
INSERT INTO sqlite_sequence VALUES('color_scheme',317);
INSERT INTO sqlite_sequence VALUES('format',1);
INSERT INTO sqlite_sequence VALUES('claim',8);
INSERT INTO sqlite_sequence VALUES('source',24);
INSERT INTO sqlite_sequence VALUES('place',1);
INSERT INTO sqlite_sequence VALUES('places_places',1);
COMMIT;
